"""Migrating...

Revision ID: 346bd7311493
Revises: 31219109e3c9
Create Date: 2019-07-06 22:52:03.479866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "346bd7311493"
down_revision = "31219109e3c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("urls", sa.Column("created_at", sa.BigInteger(), nullable=True))
    op.add_column("urls", sa.Column("updated_at", sa.BigInteger(), nullable=True))
    op.add_column("users", sa.Column("created_at", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    op.drop_column("urls", "updated_at")
    op.drop_column("urls", "created_at")
    # ### end Alembic commands ###
