"""Migrating...

Revision ID: 4cea0d34af8f
Revises: fbb26aa0711f
Create Date: 2019-07-06 14:37:22.440923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cea0d34af8f'
down_revision = 'fbb26aa0711f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
