"""Migrating...

Revision ID: aa5cffbc8a52
Revises: 346bd7311493
Create Date: 2019-07-08 22:00:24.736638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aa5cffbc8a52"
down_revision = "346bd7311493"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("urls", sa.Column("url_alias", sa.String(), nullable=True))
    op.create_index("idx_url_alias", "urls", ["url_alias"], unique=True)
    op.drop_index("idx_url_hash", table_name="urls")
    op.drop_column("urls", "url_hash")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "urls", sa.Column("url_hash", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_index("idx_url_hash", "urls", ["url_hash"], unique=True)
    op.drop_index("idx_url_alias", table_name="urls")
    op.drop_column("urls", "url_alias")
    # ### end Alembic commands ###
