"""Migrating...

Revision ID: d57ffa1ea737
Revises: 4cea0d34af8f
Create Date: 2019-07-06 14:39:22.578831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57ffa1ea737'
down_revision = '4cea0d34af8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_username', 'users', ['username'], unique=True)
    op.create_table('urls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shortened_url', sa.String(), nullable=True),
    sa.Column('full_url', sa.String(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shortened_url', 'urls', ['shortened_url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_shortened_url', table_name='urls')
    op.drop_table('urls')
    op.drop_index('idx_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
