"""Migrating...

Revision ID: fbb26aa0711f
Revises: f5cbf2f7fc4d
Create Date: 2019-07-06 14:35:10.244796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fbb26aa0711f"
down_revision = "f5cbf2f7fc4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
